name: imweb-component

on:
  push:
    branches: [ master ]
    paths:
      - 'public/utils/util.js'
      - 'public/index.css'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: ${{ secrets.GITHUB_TOKEN }}

      # 여기에 필요한 빌드 스크립트나 추가 작업을 추가할 수 있습니다.
      # 예: npm install, npm run build 등

      - name: imweb-component
        run: |
          git config user.name "onepunch-tk"
          git config user.email "86tkstar@gmail.com"
          git add public/utils/util.js public/index.css
          git commit -m "Update index.js and index.css" || echo "No changes to commit"
          git push
