name: imweb-component

on:
  push:
    branches: [ master ]
    paths:
      - 'public/utils/util.js'
      - 'public/index.css'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Github checkout
        uses: actions/checkout@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: imweb-component
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.email "86tkstar@gmail.com"
          git config user.name "onepunch-tk"
          git add public/utils/util.js public/index.css
          git commit -m "Update index.js and index.css" || echo "No changes to commit"
          git push
